all:
  vars:
    ansible_user=admin
    ansible_ssh_pass=xxxxxxxx
  children:
    ungrouped:
      hosts:
        web1:
          ansible_host: '{{ansible_host1}}'
        web2:
          ansible_host: '{{ansible_host2}}'
        haproxy:
          ansible_host: '{{ansible_host3}}'     